# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DM545/DM871 (F24) 
email: marco@imada.sdu.dk
description: "Linear and Integer Programming: Course on Mathematical Programming at Master Level in Computer Science at University of Southern Denmark"
tagline: A Jekyll template for course websites
author: Marco Chiarandini
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://dm561.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://dm871.github.io"
# url: "https://imada.sdu.dk/"
# baseurl: "/u/marco/Teaching/AY2022-2023/DM871"

exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "vendor"]

# Theme settings
# remote_theme: just-the-docs/just-the-docs@v0.7.0
theme: just-the-docs
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
favicon_ico: "/assets/images/favicon.ico"
aux_links:
  Marco Chiarandini:
    - 'https://imada.sdu.dk/u/marco'
  # Just the Class on GitHub:
  #  - 'https://github.com/kevinlin1/just-the-class'
footer_content:
# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%Y-%m-%d %H:%M" # %b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Back to top link
# back_to_top: true
# back_to_top_text: "Back to top"

# nav_external_links:
#  - title: Schedule
#    url: ./assets/schedule.html
#    nav_order: 2

# Collections for website data
collections:
  staffers:
  modules:
  #schedules:
  announcements:
  tutorials:
    permalink: "/:collection/:path/"
    output: true


# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  # - scope:
  #     path: ''
  #     type: schedules
  #   values:
  #     layout: schedule
  - scope:
      path: ''
      type: modules
    values:
      layout: module  
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement


just_the_docs:
  collections:
    tutorials:
      name: Tutorials
      nav_fold: true
      # nav_exclude: true
        


compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false




kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false